main.js

The debug logging was being written to stdout before fluid.doLog was re-written.
Moving the require statements for logging.js before gpii-windows didn't work because getting the settings directory in logging.js depends on the windows context.

GPII-2200: Moved debug logging to after the fluid.log redirect has been set

---

README.md
package.json
provisioning/Build.ps1
provisioning/Installer.ps1
tests.js

Several fixes that make the provisioning process and testing work.
Note that windowsBootstrapURl is now pointing to my GPII-2287 branch of windows and that this needs to be updated once it's merged into windows/hst-2017 (see https://github.com/GPII/windows/pull/111)

GPII-2287 and GPII-2289: Fix provisioning and tests

---

package.json
provisioning/Installer.ps1

Also, this includes:
* updated refs of infusion and node-jqunit
* GPII-2084: Added electron-edge dependency
* GPII-2537: Build the proximity listener before creating installer

Full update of gpii-app with the last versions of both windows and universal

---

.npmrc
package.json
src/main/menu.js
src/main/utils.js

In order to use Electron 1.8.4, re-contextualizing for the Electron menu template object is needed.
This is caused by a [change](https://github.com/electron/electron/blob/v1.8.4/lib/browser/api/menu.js#L170) in an Array check to a less graceful one.
Infusion expansion uses a different context which causes this check to fail.

GPII-2937: Migration to Electron 1.8.4

---

provisioning/Installer.ps1

The installer will be copied from the "installer" folder into the
original project folder. For instance, on CI, the installer is being
created under c:/installer and the git project is in c:/vagrant. With
this change the installer will be copied from the c:/installer/output
folder into c:/vagrant/installer.
This allows us to publish the installer as an output build artifact.

GPII-3191: Copy the resulting installer into the project folder

---

testData/qss/settings.json
tests/PreferencesGroupingTests.js

Works with https://github.com/GPII/windows/pull/190 to make the QSS set the correct values.
There's still a problem where the range of the DPI values are dynamic.

GPII-3230: The DPI scaling fixes

---

main.js

Fixes this error, when running the "Reset" desktop link while in high-contrast:
```
Reset: Error occurred during logout: Unable to cast COM object of type 'System.__ComObject' to interface type
'System.Management.IWbemServices'. This operation failed because the QueryInterface call on the COM component
for the interface with IID '{9556DC99-828C-11CF-A37E-00AA003240C7}' failed due to the following error: The application
called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD)).
```
https://issues.gpii.net/browse/GPII-3455

GPII-3455: Calling the reset code in the next tick.

---

Vagrantfile
main.js
package.json
tests/IntegrationTests.js

Ensure that `gpii-app` is requiring modules that it explicitly depends on:
- if `gpii-universal` is needed - use `gpii-windows` to load it
- include other missing dependencies - `ws`
Also restore installer creation which was stopped to improve CI tests debugging speed.

Fix app dependencies

---

src/main/dialogs/basic/dialog.js
src/main/dialogs/basic/offScreenHidable.js

``` As of 01.07.2019 PSP status meeting, this should be included in Morphic version 1.1```
Somewhat partial fix for GPII-3607.
It is partial as in case there's a display bellow the primary display that has `scaleFactor` different from the `scaleFactor` of the primary display, it will be positioned and sized correctly, but there also will be a flicker of QS dialogs.
Detailed description of the solution can be found in the [Jira ticket](https://issues.gpii.net/browse/GPII-3607?focusedCommentId=36601&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-36601)

GPII-3607: Use a safer mechanism when moving a dialog from off-screen

---

src/main/dialogs/quickSetStrip/qssDialog.js

Added missing margin to the close button width, which solves the low-resolution issue.

GPII-3521: QuickStrip is not fully visible on the screen

---

messageBundles/gpii-app-qss-settings_bg.json
messageBundles/gpii-app-qss-settings_en.json
siteconfig.json5
src/main/dialogs/quickSetStrip/qssDialog.js
src/main/qss.js
src/main/siteConfigurationHandler.js
src/renderer/qss/js/index.js
src/renderer/qss/js/qss.js
src/renderer/qss/js/qssServiceButtons.js
src/renderer/qssWidget/js/qssWidget.js
testData/qss/settings.json
tests/QssTestDefs.js
tests/fixtures/qssSettings.json

* Created a new service button called **"Quick Folders"** for access to the quick cloud folder.
* Added all the required changes in order to be able to use **siteConfig** in all of the widgets _(this will be reused in any other button that needs siteConfig)_

GPII-3777: Quick Folders (via URL)

---

messageBundles/gpii-app-messageBundle_en.json

* Renamed the "Learn More..." links to "Help / Learn more"

GPII-3788: Rename the "Learn More" links in the widget popups

---

testData/qss/settings.json

* Fixed the identical tabindexes, and move to a more convenient numbering system
* Moved the Quick Folders button next to the system ones, because its a system one (no popup, etc.)

GPII-3786: Fix the tab indexing of the settings

---

messageBundles/gpii-app-qss-settings_en.json
tests/QssTestDefs.js

* Quick Folder's button name changed

GPII-3797: "Quick Folders" should be "Open Quick Folder"

---

configs/app.base.json
src/main/app.js
src/main/metrics.js

Captures metrics of interactions with the QSS, such as the show/hide of the QSS and widgets, and setting changes.
To test: Metrics can be sent to a file, set via `GPII_EVENT_LOG` environment variable.
(A "nice to have" feature was to determine if a setting was set via the QSS or not - the implementation of this became tricky so I've scrapped it)

GPII-3778: User interface metrics capture.

---

src/main/common/utils.js

When Read&Write gold is docked at the top, the QSS is positioned incorrectly.
This PR fixes it (I've only tested with magnifier)

GPII-3686: Offset windows to consider windows docked at the top or left

---

trayButton/tray-button.c

Task button always assumed the notification area was at the right of the task list - now it doesn't.

NOJIRA: Task button supports right-to-left layout.

---

messageBundles/gpii-app-qss-settings_en.json

* Fixed the word "Grey" to "Gray" in the High Contrast menu

GPII-3884: QSS High Contrast menu misspell fix

---

siteconfig.json5
src/main/qss.js

Added option to show QSS on startup:
* Added new siteConfig value called showQssOnStart (boolean)
* Using set value to determine to show QSS or not on Morphic's startup

GPII-3872: Add siteConfig option for QSS open on startup

---

siteconfig.json5
src/renderer/qss/js/qssServiceButtons.js

Override the user's preferred browser for the quick docs link in the QS.
(optimised for implementation speed, rather than engineering brilliance)

GPII-4028: Option to use chrome instead of default browser, for quick docs

---

package.json
provisioning/Build.ps1

This windows update brings the ability to build and run the tests in
Windows 10 1903.

GPII-4178: Updated windows reference

---

messageBundles/gpii-app-qss-settings_bg.json
messageBundles/gpii-app-qss-settings_en.json
siteconfig.json5
src/main/app.js
src/main/dialogs/basic/dialog.js
src/renderer/common/js/utils.js
src/renderer/qss/js/qss.js
src/renderer/qss/js/qssServiceButtons.js
testData/qss/settings.json
tests/fixtures/qssSettings.json
tests/qss/QssTestDefs.js
tests/qss/qssCommons-navigationTests.js
tests/qss/qssWidget-urlDropboxTests.js
tests/qss/qssWidget-urlGoogleDriveTests.js
tests/qss/qssWidget-urlOneDriveTests.js

GPII-4189, GPII-4190, GPII-4191: All three url based buttons (My Google Drive, My One Drive, and My Dropbox) are added
* Added siteConfig variables for all the buttons under qss.urls
* Added ids to be used in the buttonList: "url-google-drive", "url-one-drive", "url-dropbox"
* Added messageBundle variables for the titles and tooltips
* Fixed some linting issues from the previous merges

GPII-4189, GPII-4190, GPII-4191: My Google Drive, My One Drive, and My Dropbox

---

package.json
siteconfig.json5
src/main/common/utils.js
src/main/dialogs/quickSetStrip/qssDialog.js
src/renderer/qss/js/qss.js
src/renderer/qss/js/qssServiceButtons.js

Added new key sequencer type custom button
* Added new "buttonType": "KEY" in the buttonList's custom type buttons
* Handling the new custom type in gpii.app.generateCustomButton as well, generating "custom-keys" type setting
* Created new gpii.qss.customKeysPresenter for the custom key setting
* Added onQssExecuteKeySequence event which uses Steve's gpii.windows.sendKeys.send() to send the keys to Windows

GPII-4135: Add new custom button type - key sequencer

---

main.js
package.json

Notes for posterity:
npm does not currently have robust support for OS-specific package dependencies in an app's package.json file.
To make the Morphic QuickStrip (gpii-app) cross-platform, the OS-specific packages have been whitelisted for their specific OS in their package.json files ("win32" for Windows, "darwin" for macOS, etc.).
These OS-specific packages have been moved from the "dependencies" section in our app's package.json file to the "optionalDependencies" section.  When executing an npm install, npm will therefore not pull in the OS-specific optionalDependencies which do not apply to the host OS.
Please note that marking our OS-specific dependencies as optional dependencies has a side-effect: if their npm installation fails, it may fail silently.  If this causes significant …

GPII-4253: Made gpii-windows package an optional (OS-whitelisted) dependency

---

siteconfig.json5
src/main/common/utils.js
src/main/dialogs/quickSetStrip/qssDialog.js
src/renderer/qss/css/qss.css
src/renderer/qss/js/qss.js
src/renderer/qss/js/qssButtons.js
testData/qss/settings.json

* Added new grid type that can be used in buttonList - "grid" for the invisible one and "grid-visible" for the gray one
* Added shortcuts:
* separator ==> |
* separator-visible ==> II
* grid ==> -
* grid-visible ==> x

GPII-4271: More Panel: Create a new type of separator (for the empty spaces in the grid)

---

Vagrantfile
package.json
src/main/gpiiConnector.js
tests/PreferencesGroupingTests.js
tests/PreferencesParsingTests.js

With [the change of PSPChannel API](https://github.com/GPII/universal/pull/826) being merged into the universal repo, gpii-app stops working with the universal master. 
PSPChannel now expects a slightly different incoming message while PSPChannel output messages stay unchanged. The PSPChannel API is [here](https://github.com/GPII/universal/blob/master/documentation/PSPChannel.md).
This pull request adjusts gpii-app to work with the new API. @Karadaliev or @krisYanachkov, I'm not sure if it covers all messages sent to PSPChannel (Local flow manager). Please have a look. Thanks.
Please don't merge this pull request directly since it is pointing to my own gpii/windows branch which pulls in the universal master branch.

GPII-3958: Adjust gpii-app to work with the new PSPChannel API.

---

Vagrantfile

This will also install Chrome in the last version of the vagrant box (2020.02.11), where Chrome is missing, see https://issues.gpii.net/browse/GPII-4425.
If you're missing Chrome and don't want to provision the machine again, run (as admin) `choco install googlechrome`

GPII-4425: Updated Vagrantfile to update Chrome and Firefox as gpii/windows does

---

src/renderer/qss/js/qssServiceButtons.js

Forcing the custom URL buttons to always use Chrome (if available).

GPII-4422: Use Chrome for MYOB

---

src/main/qss.js

This fixes the small bug when you open the Color Vision first and then any menuWidget type button (Languages, High Contrast, etc.) and the color vision footerTip still shows.

GPII-4474: Fix the footerTip issue (showing on every menuWidget)
