GPII/gpii-app

src/app.js

@javihernandez Bern requested this for HST.  Thanks!

GPII-1596: Made the context menu show on both click and right click.

---

src/app.js

GPII-2348: Notification about port 8081 is already in use doesn't work all the time

---

Vagrantfile

More info [here](https://github.com/GPII/gpii-app/pull/13)

NOJIRA: Update vagrant box

---

configs/app.dev.json
configs/app.production.json
configs/app.testing.json
main.js
package.json
tests.js
tests/IntegrationTests.js

Works with https://github.com/GPII/windows/pull/161

GPII-2568: Updated references to universal with gpii-universal

---

src/main/quickSetStrip/qss.js

Tiny fix to make the screen zoom button work the first time.

NOJIRA: fixed DPI scale first click

---

configs/app.base.json
src/main/app.js

This enables the "Reset to Standard" functionality at startup.

GPII-3454: Switched to the production configuration of universal

---

Gruntfile.js
messageBundlesCompiler.js
package.json
scripts/compileMessageBundles.js
scripts/shared/messageBundlesCompiler.js
tests/MessageBundlesCompilerTests.js

Here's a first implementation of this. There is a lot of room for improvements, so let me know your thoughts on this.

GPII-3550: Converted messageBundlesCompiler.js into a script

---

.gitignore
trayButton/.gitignore

Ignoring the Debug and Release directories.

GPII-3540: Added tray button build turds to .gitignore

---

configs/app.base.json
package.json
siteconfig.json5

This includes several changes that need to get in in order to produce the 1.0.1 release.

GPII-3635: Final tune-up for Morphic 1.0.1

---

src/main/gpiiConnector.js

Also reported as GPII-3662.
Cherry-picked from https://github.com/GPII/gpii-app/pull/77/commits/7c2f4672c8eb988d19669dc1b7457256cfaa1818
This is the one that makes the PSP to use the DPI range and list of languages from the OS in the same way the QS does.

GPII-3608: Set proper values for both Scale factor and language preferences

---

src/renderer/qssWidget/css/qssMenuWidget.css
src/renderer/qssWidget/js/qssMenuWidget.js

* Added default setting marker (star icon) for qssMenuWidget - used in Contrast and Language menus.

GPII-3683: Add indication for default setting in some menus

---

messageBundles/gpii-app-qss-settings_en.json

A simple change of the tooltip message of the App/Text Zoom button

GPII-3772: Change the zoom button's tooltip

---

testData/qss/settings.json

* Changed the screen capture behavior from full screen, to selected region

GPII-3794: Changing the screen capture button's commands

---

messageBundles/gpii-app-qss-settings_en.json

GPII-3800: Grammatic text changes in the AppZoom and Quick Folders

---

siteconfig.json5

It includes:
* Updated the default URL for QUICK FOLDER
* Updated the keyedOut message
DO NOT MERGE YET - I'm still waiting for confirmation if we want these to be included in trunk

GPII-3804: Two minor updates to the siteconfig file

---

messageBundles/gpii-app-qss-settings_en.json

* Text changes to the Language and High Contrast menu

GPII-3808: March 19 Updates to QuickStrip texts

---

messageBundles/gpii-app-qss-settings_en.json
testData/qss/settings.json
tests/fixtures/qssSettings.json

- Remove Light and Dark Gray from High Contrast menu

GPII-3837: Remove Light and Dark Gray from High Contrast menu

---

messageBundles/gpii-app-qss-settings_en.json

* Screen Capture button's tooltip changes

GPII-3820: Change the screen capture button's tooltip

---

src/renderer/qssWidget/css/qssMenuWidget.css
src/renderer/qssWidget/css/qssStepperWidget.css
src/renderer/qssWidget/js/qssWidget.js

* Very small UX adjustments to the stepper and menu widgets

GPII-3840: Screen Zoom Menu dots clipped on the larger resolutions

---

messageBundles/gpii-app-messageBundle_bg.json
messageBundles/gpii-app-messageBundle_en.json

- Changed the text of the GPII tray icon fol logged in users.

GPII-3825: Updates to gpii-app Tray icon

---

src/main/dialogs/basic/resizable.js

* changing the scale factor only if its called properly from the QSS wrapper

GPII-3822: QuickStrip not re-scaling on the fly

---

messageBundles/gpii-app-messageBundle_bg.json
messageBundles/gpii-app-messageBundle_en.json
src/main/menu.js
tests/IntegrationTestDefs.js

- Changed text of the tray menu for logged in users
- Drop the section for selecting Preference Sets
- Fixed some tests, other are commented and need rework when is clear the expected behavior

GPII-3826: Updates to gpii-app tray menu

---

src/main/qss.js
tests/QssTestDefs.js

- Show notification warning only one time per session
- Notification is not showing when user is keyed in.

GPII-3796: The change language warning keeps appearing all the time

---

src/main/logging.js

See https://issues.gpii.net/browse/GPII-3954

GPII-3954: Replaced fluid.doLog monkey-patch with an event listener

---

src/main/tray.js
trayButton/tray-button.c

This just adds some logging to the task bar button.

GPII-3873: Added logging to the taskbar button.

---

messageBundles/gpii-app-messageBundle_en.json
src/renderer/qssWidget/js/qssStepperWidget.js

See https://issues.gpii.net/browse/GPII-3973

GPII-3973: Minor tweak to lowest/highest user messages

---

src/main/common/utils.js
src/main/dialogs/quickSetStrip/qssWidgetDialog.js
src/renderer/qssWidget/js/qssVolumeWidget.js
src/renderer/qssWidget/js/qssWidget.js
testData/qss/settings.json

* Added Ipc Listener to get the current Windows volume value on opening the widget

GPII-3881: Volume Control v2

---

messageBundles/gpii-app-qss-settings_en.json
siteconfig.json5
src/renderer/common/js/utils.js

* DocuMorph launcher fixes
* Syntax Changes
* Re-order of the buttons

GPII-4008: Morphic 1.2.0 EARLY Candidate - Reported issues - DocuMorph and Syntax Changes

---

messageBundles/gpii-app-qss-settings_en.json
src/renderer/qssWidget/css/qssMenuWidget.css
src/renderer/qssWidget/css/qssStepperWidget.css
src/renderer/qssWidget/css/qssUSBWidget.css
src/renderer/qssWidget/js/qssVolumeWidget.js

- G1 - Scroll problem still exists for language menu
- G3 - If muted - then hit vol up or down should “unmute” and take you back to previous volume
-  Added footer link to 'Zoom top window' widget
- A scroll bar appears on USB widget without need
- K4 - Volume sound when reached max doesn’t give beep alert sound and doesn’t flash in red,same with when volume reaches min

GPII-4008: Morphic 1.2.0 EARLY Candidate

---

messageBundles/gpii-app-qss-settings_en.json
siteconfig.json5
src/renderer/qss/css/qss.css
testData/qss/settings.json

- Added new button 'Translate Tools'
- Changes to the LANGUAGE button

GPII-4019: Create Translate button & change Language naming

---

siteconfig.json5

The default values can be found here: https://docs.google.com/spreadsheets/d/1jtjJX1ZXycaPR_jIdFJi3Qzq-sLeqN_2dvh5q5YtfP8
See https://issues.gpii.net/browse/GPII-4024 for more info.

GPII-4024: Updated siteConfig according to the default values

---

src/renderer/qss/js/qss.js

Added button presenter to "MS Word Simplify" widget.

GPII-4042: Word Simplification don't have a working [changed] indicator

---

messageBundles/gpii-app-qss-settings_en.json

* Changed the tooltip of the Reset service button

GPII-4067: Change Tool Tip for the Reset-To-Standard button

---

src/renderer/qssWidget/js/qssMenuWidget.js
src/renderer/qssWidget/js/qssOfficeWidget.js
src/renderer/qssWidget/js/qssScreenCaptureWidget.js
src/renderer/qssWidget/js/qssStepperWidget.js
src/renderer/qssWidget/js/qssToggleWidget.js
src/renderer/qssWidget/js/qssVolumeWidget.js

* Changed 'settingAlter' source namespace to 'fromWidget' in every widget

GPII-4001: Naming of change source "settingAlter" in GPII app is unclear

---

messageBundles/gpii-app-qss-settings_bg.json
messageBundles/gpii-app-qss-settings_en.json
siteconfig.json5
src/renderer/qss/js/qss.js
src/renderer/qss/js/qssServiceButtons.js
testData/qss/settings.json
tests/fixtures/qssSettings.json
tests/qss/QssTestDefs.js
tests/qss/qssCommons-navigationTests.js
tests/qss/qssWidget-customizeQuickstripTests.js

Added new url based service button for opening the Customize Quickstrip web page.

GPII-4197: Add button Customize Quickstrip (Launches Web Tool)

---

src/renderer/common/css/titlebar.css

* Moved the [X] button on the about dialog

GPII-4287: [B5 from 20th dec installer]Investigate & fix x mark on the pop-up

---

Vagrantfile
package.json

Testing if this solves the build issues reported at https://github.com/GPII/gpii-app/pull/178#issuecomment-588409356

GPII-4367: Testing javihernandez/windows#GPII-4367

---

siteconfig.json5

See https://issues.gpii.net/browse/GPII-4498

GPII-4498: Updated cloudFolder link
